name: Continuous Integration

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install Dependencies
      run: |
        cd backend
        npm install
    - name: Run tests and collect coverage
      run: |
        cd backend
        npm run test 
    - name: Check if coverage decreased
      id: coverage_check
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./backend/coverage/lcov.info
        threshold: 0
    - name: Upload coverage to artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: backend/coverage/lcov-report/

  code-format:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install Dependencies
      run: |
        cd backend
        npm install
    - name: Check format status
      id: check_format
      run: |
        cd backend
        if [ "$(npm run format:check)" == "0" ]; then
          echo "::set-output name=formatted::true"
        else
          echo "::set-output name=formatted::false"
        fi
    - name: Format code
      if: steps.check_format.outputs.formatted == 'false'
      run: |
        cd backend
        npm run format
    - name: Create Pull Request with formatted code
      if: steps.check_format.outputs.formatted == 'false'
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Format backend code
        title: '[Bot] Format Backend Code'
        body: 'Automated code format update.'
        branch: format-code-patch
        labels: automated pr
