name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # 更新 Node.js 版本

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Run tests
      run: npm run test
      working-directory: ./backend

    - name: Generate test coverage
      run: npm run coverage
      working-directory: ./backend

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./backend/coverage

    - name: Check code formatting
      run: npm run format:check
      working-directory: ./backend

    - name: Format code
      if: failure()
      run: npm run format
      working-directory: ./backend

    - name: Commit formatted code
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # 使用 PAT 來推送更改
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -am "style: auto format code"
        git push
