name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Run tests
      run: npm run test
      working-directory: ./backend

    - name: Generate test coverage
      run: npm run coverage
      working-directory: ./backend

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./backend/coverage

    - name: Check code formatting
      id: format-check
      run: npm run format:check
      working-directory: ./backend

    - name: Format code
      if: steps.format-check.outcome == 'failure'
      run: npm run format
      working-directory: ./backend

    - name: Commit formatted code
      if: steps.format-check.outcome == 'failure'
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -am "style: auto format code"
        git push

    - name: Check coverage difference
      run: |
        echo "Comparing coverage..."
        if [ -f "./backend/coverage/base-coverage.txt" ]; then
          BASE_COVERAGE=$(cat ./backend/coverage/base-coverage.txt)
        else
          BASE_COVERAGE=0
        fi
        CURRENT_COVERAGE=$(jq '.total.lines.pct' ./backend/coverage/coverage-summary.json)
        echo "Base coverage: $BASE_COVERAGE%"
        echo "Current coverage: $CURRENT_COVERAGE%"
        if (( $(echo "$CURRENT_COVERAGE < $BASE_COVERAGE" | bc -l) )); then
          echo "Coverage decreased. Failing the job."
          exit 1
        else
          echo "Coverage is sufficient. Saving new base coverage."
          echo "$CURRENT_COVERAGE" > ./backend/coverage/base-coverage.txt
        fi
      working-directory: ./backend

    - name: Cleanup
      run: echo "Cleaning up..."
